Repository gdscwce/Laptop-Specification-api, pull requests merged in 2022-10, with the labels that each got.

#65 Added Dell G15
  data.json
Labels: hacktoberfest2022, hacktoberfest

#64 Added new laptop specification
  data.json
Labels: hacktoberfest2022, hacktoberfest

#66 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest

#67 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest-accepted

#68 Add Macbook specs
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#69 Updated data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#98 Added new Laptop-Specification
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#99 added my laptop description
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#94 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#101 Acer
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#106 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#108 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted
