Repository gdscwce/Laptop-Specification-api, pull requests merged in 2022-09, with the labels that each got.

#2 Update data.json
  data.json
Labels: enhancement

#5 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfestAccepted

#7 added laptop info
  data.json
Labels: hacktoberfest, hacktoberfestAccepted

#9 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfestAccepted

#8 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfestAccepted

#10 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfestAccepted

#11 Dell 5518 added
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#12 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#13 added asus tuf a15
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#14 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#15 HP Pavilion added
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#16 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#17 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#18 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#19 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#20 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#22 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#23 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest

#24 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#25 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#26 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#27 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#30 updated data
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#28 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#31 Updated Lenovo Ideapad Flex 5
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#32 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#33 updating data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#34 Added mac Mini specs.
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#35 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#36 Updated Data.json to add Acer Aspire 7
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#37 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#38 new Laptop Specs added
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#39 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#41 Added My Laptop Specifications
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#42 aus rog is added
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#43 New update
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#44 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest

#45 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#46 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#53 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#51 Added HP Pavillion AU008TX
  CONTRIBUTING.md
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#54 Update
  data.json
Labels: hacktoberfest2022, hacktoberfest-accepted

#55 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#49 Update data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#57 Update
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#58 Update
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#56 Update
  data.json
Labels: hacktoberfest2022, hacktoberfest

#59 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#60 Updated and fixed data.json
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#61 Add: Asus TUF A15
  data.json
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#62 Update data.json
  data.json
Labels: hacktoberfest, hacktoberfest-accepted

#63 new Laptop Specification added
  data.json
Labels: hacktoberfest, hacktoberfest-accepted
